### ISSUE TITLE
Support Kelvin as temperature input

### ISSUE THREAD

**Issue by smudge** [smudge/nightlight#12]
In addition to a number from 0-100 (the macOS config format) we can use a more standardized expression of color temperature, like so:

```
nightlight temp 4000K
```

Lower and upper bounds should be these (parity with Linux/GSettings night light):

```
nightlight temp 3500K
nightlight temp 6000K
```

**Comment by tjtelan** [comment]
I made an attempt. I didn't touch your error messages since I wasn't sure where else they were being used. However, I do bounds checking for kelvin temps outside of your specified range. LMK what you think. Thanks!
