### ISSUE TITLE
Why does brew install smudge/smudge/nightlight tries to read my github.com credentials? 

### ISSUE THREAD

**Issue by tuxmanu** [smudge/nightlight#19]
I just tried to install nighlight which opens up my credentials helper and asking for my github.com credentials.
![nightlight](https://user-images.githubusercontent.com/46025208/154258284-fa6080a7-f791-42a5-86e4-854caa3a8b82.png)

**Comment by smudge** [comment]
Not sure. The formula is here:

https://github.com/smudge/homebrew-smudge/blob/master/Formula/nightlight.rb

It's connecting to `smudge/homebrew-smudge` (a repo - that's the "tapping smudge/smudge" bit) and then downloads the file under the `url` opt (also hosted on GitHub under this repo's releases). I don't know why one of those would ask for your credentials again.
