### ISSUE TITLE
Brew Install Error

### ISSUE THREAD

**Issue by bluecursor** [smudge/nightlight#20]
mymac ~ % brew install smudge/smudge/nightlight
Error: Git is unavailable

**Comment by smudge** [comment]
Any luck here? Did you run `brew install git` first, and are you able to run other `git` commands?

If you can't get it working, it would be better to open a new issue over in this repo:
https://github.com/smudge/homebrew-smudge/

The formula in question is here:
https://github.com/smudge/homebrew-smudge/blob/master/Formula/nightlight.rb
